// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLFXj1LSOK_MMR34zF_lEe8B2EZovCLQ',
    appId: '1:428580172185:web:ed83eea2fa322e19b02308',
    messagingSenderId: '428580172185',
    projectId: 'safty-helmet-8811',
    authDomain: 'safty-helmet-8811.firebaseapp.com',
    storageBucket: 'safty-helmet-8811.appspot.com',
    measurementId: 'G-X1FED6HT2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXF1Lf4r9S3d_yDzTZlQx2_X0GkWFTPyY',
    appId: '1:428580172185:android:c50f915f542fd43bb02308',
    messagingSenderId: '428580172185',
    projectId: 'safty-helmet-8811',
    storageBucket: 'safty-helmet-8811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqG5haCTkO9f0HQwYnOJTcT_TnEyoAH1o',
    appId: '1:428580172185:ios:eb02105c6d73b594b02308',
    messagingSenderId: '428580172185',
    projectId: 'safty-helmet-8811',
    storageBucket: 'safty-helmet-8811.appspot.com',
    iosBundleId: 'com.example.saftyHelmet',
  );
}
